version: '3'

services:
    # data container is a workaround for docker issue: https://github.com/docker/docker/issues/2259
    data:
        image: bitnami/minideb:jessie
        volumes:
            - .:/var/www/symfony:rw
            - ./app/data/mysql:/var/lib/mysql:rw
            - ./app/data/redis:/data:rw
            - ./app/data/nginx:/var/lib/nginx:rw
        command: bash -c "chown -R 1000:33 /var/www/symfony/app/cache; chown -R 1000:33 /var/www/symfony/app/logs; chown -R 1000:33 /var/lib/nginx; chown -R 999:999 /var/lib/mysql; chown -R 999:999 /data; sleep 30"
    php:
        restart: always
        build: ./docker/php-fpm
        depends_on:
          - data
        volumes:
            - .:/var/www/symfony:rw
        tty: true
        stdin_open: true
    nginx:
        restart: always
        build: ./docker/nginx
        depends_on:
          - data
          - php
        expose:
            - 80
        volumes:
            - .:/var/www/symfony:ro
            - ./app/data/nginx:/var/lib/nginx:rw
        environment:
            - VIRTUAL_HOST=${VIRTUAL_HOST}
            - VIRTUAL_NETWORK=nginx-proxy
            - VIRTUAL_PORT=80
            - LETSENCRYPT_HOST=${VIRTUAL_HOST}
            - LETSENCRYPT_EMAIL=anton@dorofeev.me
        networks:
            - default
            - proxy-tier
    db:
        restart: always
        build: ./docker/mysql
        depends_on:
          - data
        volumes:
            - ./app/data/mysql:/var/lib/mysql:rw
        expose:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: password
    redis:
        restart: always
        build: ./docker/redis
        depends_on:
          - data
        volumes:
            - ./app/data/redis:/data:rw
        expose:
            - 6379

networks:
    proxy-tier:
        external:
            name: nginx-proxy
