version: '2'

volumes:
    symfony_logs:
        driver: local
    symfony_cache:
        driver: local
    nginx_logs:
        driver: local
    mysql_data:
        driver: local
    redis_data:
        driver: local
    ssh_profile:
        driver: local


services:
    # workaround for docker issue https://github.com/docker/docker/issues/2259
    data:
        image: debian:jessie
        volumes:
            - .:/var/www/symfony
#            - symfony_logs:/var/www/symfony/app/logs
#            - symfony_cache:/var/www/symfony/app/cache
            - ./app/data/mysql:/var/lib/mysql
            - ./app/data/redis:/data
        command: bash -c "chown -R 1000:33 /var/www/symfony/app/cache; chown -R 1000:33 /var/www/symfony/app/logs; chown -R 999:999 /var/lib/mysql; chown -R 999:999 /data; sleep 120"
        tty: true
        stdin_open: true
    php:
        restart: always
        build: ./docker/php-fpm
        depends_on:
          - data
        volumes_from:
          - data:rw
        volumes:
            - symfony_cache:/var/log/nginx
        tty: true
        stdin_open: true
    nginx:
        restart: always
        build: ./docker/nginx
        depends_on:
          - data
          - php
        expose:
            - 80
        volumes_from:
            - data:ro
#        volumes:
#            - nginx_logs:/var/log/nginx
        environment:
            - VIRTUAL_HOST=${VIRTUAL_HOST}
            - VIRTUAL_NETWORK=nginx-proxy
            - VIRTUAL_PORT=80
            - LETSENCRYPT_HOST=${VIRTUAL_HOST}
            - LETSENCRYPT_EMAIL=anton@dorofeev.me
        networks:
            - default
            - proxy-tier
    db:
        restart: always
        build: ./docker/mysql
        depends_on:
          - data
        volumes_from:
            - data:rw
        expose:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: password
    rabbit:
        image: adorofeev/rabbitmq-delayed
        expose:
            - 5672
            - 15672
    redis:
        restart: always
        build: ./docker/redis
        depends_on:
          - data
        volumes_from:
          - data:rw
        expose:
            - 6379

networks:
    proxy-tier:
        external:
            name: nginx-proxy
