<?php

namespace AppBundle\Repository;

/**
 * Ec2InstanceHashrateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ec2InstanceHashrateRepository extends \Doctrine\ORM\EntityRepository
{
}
