<?php

namespace AppBundle\Repository;

/**
 * Ec2InstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ec2InstanceRepository extends \Doctrine\ORM\EntityRepository
{
}
