<?php

namespace AppBundle\Repository;

/**
 * Ec2InstanceHashrateStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ec2InstanceHashrateStatsRepository extends \Doctrine\ORM\EntityRepository
{
}
