<?php

namespace AppBundle\Repository;

/**
 * SpotPriceHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpotPriceHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
