services:
    app.admin.ec2_instance:
        class: AppBundle\Admin\Ec2InstanceAdmin
        arguments: [~, AppBundle\Entity\Ec2Instance, AppBundle:Ec2InstanceAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Ec2Instance }

    app.admin.ec2_instance_hashrate:
        class: AppBundle\Admin\Ec2InstanceHashrateAdmin
        arguments: [~, AppBundle\Entity\Ec2InstanceHashrate, AppBundle:Ec2InstanceHashrateAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Ec2InstanceHashrate }

    app.admin.ec2_instance_hashrate_stats:
        class: AppBundle\Admin\Ec2InstanceHashrateStatsAdmin
        arguments: [~, AppBundle\Entity\Ec2InstanceHashrateStats, AppBundle:Ec2InstanceHashrateStatsAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Ec2InstanceHashrateStats }
