FROM percona

ADD mysqld.cnf /etc/mysql/percona-server.conf.d/

#RUN rm -rf /var/lib/mysql/*
#RUN chown -R mysql. /var/lib/mysql
#RUN chmod -R 777 /var/lib/mysql
#RUN chmod -R 777 /var/lib/mysql*
#RUN apt update; apt install vim -y

#CMD ["sleep", "900"]
