old_sound_rabbit_mq:
    connections:
        default:
            host:     "%rabbitmq.host%"
            port:     "%rabbitmq.port%"
            user:     "%rabbitmq.user%"
            password: "%rabbitmq.password%"
            vhost:    "%rabbitmq.vhost%"
            lazy:     true
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0

            #requires php_sockets.dll
            use_socket: false # default false
    producers:
        spot_price_history:
            connection:       default
            exchange_options: {name: 'spot_price_history', type: 'direct'}
#        phone_call:
#            connection:       default
#            exchange_options: {name: 'phone_call', type: 'x-delayed-message', arguments: {x-delayed-type: ['S', 'direct']}}
    consumers:
        spot_price_history:
            connection:       default
            exchange_options: {name: 'spot_price_history', type: 'direct'}
            queue_options:    {name: 'spot_price_history'}
            callback:         spot_price_history_consumer
#        phone_call:
#            connection:       default
#            exchange_options: {name: 'phone_call', type: 'x-delayed-message', arguments: {x-delayed-type: ['S', 'direct']}}
#            queue_options:    {name: 'phone_call'}
#            callback:         process_phone_call_event_consumer
